'use client'

import * as React from 'react';
import { AppLayout } from "./components/AppLayout"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { red } from '@mui/material/colors';
// import { ThemeProvider, createTheme } from '@mui/material/styles';

import { unstable_createMuiStrictModeTheme } from '@mui/material/styles';

import { ThemeUIProvider } from 'theme-ui';
// import { createTheme as materialCreateTheme, THEME_ID } from '@mui/material/styles';
import {
  ThemeProvider as MaterialThemeProvider,
  createTheme as materialCreateTheme,
  THEME_ID,
} from '@mui/material/styles';

// const theme = unstable_createMuiStrictModeTheme();

// const theme = createTheme({
//   palette: {
//     primary: {
//       main: "#4527a0",
//     },
//     secondary: {
//       main: "#ffc107", // Your desired secondary color
//     },
//   },
// });

const themeUITheme = {
  fonts: {
    body: 'system-ui, sans-serif',
    heading: '"Avenir Next", sans-serif',
    monospace: 'Menlo, monospace',
  },
  colors: {
    text: '#000',
    background: '#fff',
    primary: '#33e',
  },
};

const materialTheme = materialCreateTheme();

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
        />
      </head>
      <body>
        {/* <AppLayout children={children}/> */}
        {/* <React.StrictMode>
        <ThemeProvider theme={theme}>
          <AppLayout children={children}/>
        </ThemeProvider>
        
      </React.StrictMode> */}
       {/* <ThemeUIProvider theme={themeUITheme}>
      <MaterialThemeProvider theme={{ [THEME_ID]: materialTheme }}> */}
        {/* <AppLayout children={children}/> */}
        {children}
      {/* </MaterialThemeProvider>
    </ThemeUIProvider> */}
      </body>
  </html>
  );
}
